services:
  graph_db:
    container_name: neo4j
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/wikiscrolls
      - NEO4J_server_memory_heap_max__size=5G
      - NEO4J_server_memory_pagecache_size=4G
      - NEO4J_PLUGINS=["graph-data-science"]
    volumes:
      - ./neo4j-volume/data:/data
      - ./neo4j-volume/import:/import
      - ./neo4j-volume/plugins:/plugins
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 3s
      timeout: 5s
      retries: 20
      start_period: 40s
    networks:
      - local

  pagerank:
    container_name: pagerank
    build: ./pagerank
    ports:
      - "3333:3000"
    depends_on:
      graph_db:
        condition: service_healthy
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
      - GIN_MODE=release
    networks:
      - cloudflared
      - local

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - cloudflared

  # Zero Trust tunnel
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    environment:
      - TZ=Asia/Jakarta
      - TUNNEL_TOKEN=${TOKEN}
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    networks:
      - cloudflared

networks:
  cloudflared:
    name: cloudflared
  local:
    name: local