services:
  pagerank:
    build: ./pagerank
    ports:
      - "8888:3000"
    environment:
      - GIN_MODE=debug
      - GORSE_URL=http://gorse:8088
      - GORSE_KEY=
    networks:
      - cloudflared
      - local

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - local

  mysql:
    image: mysql/mysql-server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: gorse
      MYSQL_USER: gorse
      MYSQL_PASSWORD: gorse_pass
    networks:
      - local

  gorse:
    image: zhenghaoz/gorse-in-one
    restart: unless-stopped
    ports:
      - 8086:8086   # gRPC port
      - 8088:8088   # HTTP port
    environment:
      # Use Redis as cache storage backend.
      GORSE_CACHE_STORE: redis://redis:6379
      # Use MySQL as data storage backend.
      GORSE_DATA_STORE: mysql://gorse:gorse_pass@tcp(mysql:3306)/gorse?parseTime=true
    command: >
      -c /etc/gorse/config.toml 
      --log-path /var/log/gorse/master.log 
      --cache-path /var/lib/gorse/master_cache.data
    volumes:
      # Mount the configuration file.
      - ./config.toml:/etc/gorse/config.toml
    depends_on:
      - redis
      - mysql
    networks:
      - local

  # backend:
  #   build: ./backend
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - cloudflared

  # Zero Trust tunnel
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    environment:
      - TZ=Asia/Jakarta
      - TUNNEL_TOKEN=${TOKEN}
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    networks:
      - cloudflared

networks:
  cloudflared:
    name: cloudflared
  local:
    name: local